import Head from 'next/head'
import Layout from '../components/Layout/layout'
import styles from '../styles/home.module.scss'
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>

        <section className={styles.sectionImg}>
          <img className={styles.image} src="/header.png" alt=""/>
        </section>

      </div>



    </>
  )
}

Home.getLayout = function getLayout(page) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}
