import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className="index">
      <Head>
        <title>Sommelier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <p>Hello, world!</p>
      </main>

      <footer className="footer">
          <p>some footer</p>
      </footer>
    </div>
  )
}

export default Home
