import Head from 'next/head'
import Card from "../components/card"

const wine = {
  name: "Montrachet Grand Cru",
  price: 4205,
  origin: "France",
  domain: "Leflaive",
  img: "/wine-placeholder.png"
}

export default function Massimo() {
  return (
    <>
      <Head>
        <title>Massimo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card wine={wine}/>
    </>
  )
}