import Head from 'next/head'
import Card from "../components/card"

const wine = {
  name: "Montrachet Grand Cru",
  price: 4205,
  origin: "France",
  domain: "Leflaive",
  flag: "/flags/FR.svg",
  img: "/romanee.png",
  
}

export default function Massimo() {
  return (
    <>
      <Head>
        <title>Massimo</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div style={{display: 'flex', margin: '100px'}}>
      <Card wine={wine}/>

      </div>
    </>
  )
}